<a href="https://colab.research.google.com/github/jhkr1/PythonML/blob/main/02_Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 02.Multiple Linear Regression

### 원-핫 인코딩

In [1]:
import pandas as pd
import numpy as np
dataset = pd.read_csv('/content/drive/MyDrive/PythonMLWokrspace/ScikitLearn/MultipleLinearRegressionData.csv')

In [3]:
dataset.head()

hour  absent    place  score
0   0.5       3     Home     10
1   1.2       4  Library      8
2   1.8       2     Cafe     14
3   2.4       0     Cafe     26
4   2.6       2     Home     22

In [12]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(drop='first'), [2])], remainder='passthrough')
X = ct.fit_transform(X)

In [14]:
X

# 1 0 Home
# 0 1 Library
# 0 0 Cafe

array([[1.0, 0.0, 0.5, 3],
       [0.0, 1.0, 1.2, 4],
       [0.0, 0.0, 1.8, 2],
       [0.0, 0.0, 2.4, 0],
       [1.0, 0.0, 2.6, 2],
       [1.0, 0.0, 3.2, 0],
       [0.0, 1.0, 3.9, 0],
       [0.0, 1.0, 4.4, 0],
       [1.0, 0.0, 4.5, 5],
       [0.0, 0.0, 5.0, 1],
       [0.0, 0.0, 5.3, 2],
       [0.0, 0.0, 5.8, 0],
       [0.0, 1.0, 6.0, 3],
       [0.0, 0.0, 6.1, 1],
       [0.0, 1.0, 6.2, 1],
       [1.0, 0.0, 6.9, 4],
       [0.0, 0.0, 7.2, 2],
       [1.0, 0.0, 8.4, 1],
       [0.0, 1.0, 8.6, 1],
       [0.0, 1.0, 10.0, 0]], dtype=object)

### 데이터 세트 분리

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)

### 학습(다중 선형 회귀)

In [18]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

### 예측 값과 실제 값 비교(테스트 세트)

In [19]:
y_pred = reg.predict(X_test)
y_pred

array([ 92.15457859,  10.23753043, 108.36245302,  38.14675204])

In [20]:
y_test

array([ 90,   8, 100,  38])

In [21]:
reg.coef_, reg.intercept_

(array([-5.82712824, -1.04450647, 10.40419528, -1.64200104]),
 5.365006706544776)

### 모델 평가

In [22]:
reg.score(X_train, y_train) # 훈련 세트

0.9623352565265527

In [23]:
reg.score(X_test, y_test)

0.9859956178877446